image: debian

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-glibc:
  image:
    name: daewok/sbcl:debian
    entrypoint: [""]
  stage: build
  script:
    - apt-get update
    - apt-get install -y libssl-dev
    - sbcl --no-sysinit --no-userinit --non-interactive --load build.lisp --eval "(clpm-build:build)"
    - mv build build-glibc
  artifacts:
    paths:
      - build-glibc/bin/clpm
    expire_in: 2 days

build-musl:
  image:
    name: daewok/sbcl:alpine
    entrypoint: [""]
  stage: build
  script:
    - apk add openssl-dev
    - sbcl --no-sysinit --no-userinit --non-interactive --load build.lisp --eval "(clpm-build:build)"
    - mv build build-musl
  artifacts:
    paths:
      - build-musl/bin/clpm
    expire_in: 2 days

release-glibc:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - mv build-glibc/bin/clpm clpm
  artifacts:
    name: clpm-${CI_COMMIT_TAG}-linux-gnu
    paths:
      - clpm
  only:
    - tags

release-musl:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - mv build-musl/bin/clpm clpm
  artifacts:
    name: clpm-${CI_COMMIT_TAG}-linux-musl
    paths:
      - clpm
  only:
    - tags
