image: daewok/sbcl:debian

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - sbcl --no-sysinit --no-userinit --non-interactive --load build.lisp --eval "(clpm-build:build)"
